### ISSUE TITLE
100k war audio, the conversion time takes 40-50s

### ISSUE THREAD

**Issue by xclidongbo** [mybigday/whisper.rn#71]
Tested using a demo of React Native. It was found that the SDK on the iOS side, under tiny's model, the converted content is inaccurate, and with 100k war audio, the conversion time takes 40-50s.

**Comment by jhen0409** [comment]
I guess the problem is related to file format, currently whisper.cpp only allow 16khz mono channel. You can redirect to [whisper.cpp](https://github.com/ggerganov/whisper.cpp), it also contains pure iOS examples, maybe there are already some issues that can help you.

Also, adding this kind of question in [discussions](https://github.com/mybigday/whisper.rn/discussions) is also welcome, if you provide enough information I can try to help.
